# Generated by Django 5.2.8 on 2026-07-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('topic', models.CharField(choices=[('massanfertigung', 'Maßanfertigung (konfigurierbare Perücke)'), ('bestandsperuecke', 'Perücke aus dem Bestand'), ('toupet', 'Haarteil'), ('pflege', 'Pflegeberatung'), ('sonstiges', 'Sonstiges')], max_length=30, verbose_name='Art der Beratung')),
                ('preferred_datetime', models.CharField(max_length=100, verbose_name='Wunschtermin')),
                ('message', models.TextField(blank=True, verbose_name='Nachricht')),
                ('consent', models.BooleanField(default=False, verbose_name='Datenschutz-Einwilligung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingegangen am')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Bearbeitet')),
            ],
            options={
                'verbose_name': 'Terminanfrage',
                'verbose_name_plural': 'Terminanfragen',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingegangen am')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Bearbeitet')),
            ],
            options={
                'verbose_name': 'Kontaktanfrage',
                'verbose_name_plural': 'Kontaktanfragen',
                'ordering': ('-created_at',),
            },
        ),
    ]
