# Generated by Django 5.1.3 on 2026-07-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp-Videoanruf'), ('zoom', 'Zoom'), ('absprache', 'Nach Absprache')], max_length=20, verbose_name='Video-Kanal'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='mode',
            field=models.CharField(choices=[('praesenz', 'Präsenz-Beratung'), ('digital', 'Digitale Beratung')], default='praesenz', max_length=20, verbose_name='Beratungsform'),
        ),
    ]
