# Generated by Django 5.2.8 on 2026-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Firmenname'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Straße und Hausnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='USt-IdNr.'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('B2C', 'B2C-Kunde'), ('B2B', 'B2B-Kunde'), ('ALL_POWER', 'All Power'), ('ADMIN', 'Administrator')], default='B2C', max_length=10, verbose_name='Rolle'),
        ),
    ]
