# Generated by Django 5.1.3 on 2026-07-30 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0010_product_stock_mode_product_stock_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Phase')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Fertigungsphase',
                'verbose_name_plural': 'Fertigungsphasen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Lieferant',
                'verbose_name_plural': 'Lieferanten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aufgenommen', 'Aufgenommen'), ('uebergeben', 'An Fremdsystem übergeben'), ('storniert', 'Storniert')], default='aufgenommen', max_length=12, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Summe')),
                ('export_status', models.CharField(choices=[('pending', 'Offen'), ('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=10, verbose_name='Übergabe')),
                ('export_ref', models.CharField(blank=True, max_length=100, verbose_name='Referenz Fremdsystem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_no', models.CharField(max_length=40, unique=True, verbose_name='Inventarnummer')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Einkaufspreis')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='Wareneingang')),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('reserviert', 'Reserviert'), ('verkauft', 'Verkauft'), ('ausgemustert', 'Ausgemustert')], default='verfuegbar', max_length=12, verbose_name='Status')),
                ('reserved_until', models.DateTimeField(blank=True, null=True, verbose_name='Reserviert bis')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Verkauft am')),
                ('sold_channel', models.CharField(blank=True, choices=[('online', 'Online'), ('studio', 'Studio')], max_length=10, verbose_name='Verkaufskanal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productionphase', verbose_name='Aktuelle Fertigungsphase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='shop.product', verbose_name='Produkt (Vorlage)')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_items', to=settings.AUTH_USER_MODEL, verbose_name='Reserviert für')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Bestandsstück',
                'verbose_name_plural': 'Bestandsstücke',
                'ordering': ['inventory_no'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Verkaufspreis')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Produkt')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem', verbose_name='Bestandsstück (Einzelstück)')),
            ],
            options={
                'verbose_name': 'Bestellposition',
                'verbose_name_plural': 'Bestellpositionen',
            },
        ),
        migrations.CreateModel(
            name='StockItemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phase', 'Fertigungsphase'), ('status', 'Status')], max_length=10)),
                ('from_value', models.CharField(blank=True, max_length=60, verbose_name='von')),
                ('to_value', models.CharField(blank=True, max_length=60, verbose_name='auf')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Historien-Eintrag',
                'verbose_name_plural': 'Historie',
                'ordering': ['-changed_at'],
            },
        ),
    ]
