# Generated by Django 5.2.8 on 2026-08-04 16:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("shop", "0010_product_stock_mode_product_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="color",
            field=models.CharField(default="", max_length=80, verbose_name="Farbe"),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="invoice_no",
            field=models.CharField(
                default="", max_length=60, verbose_name="Rechnungsnummer"
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="length",
            field=models.CharField(default="", max_length=60, verbose_name="Länge"),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="product_name",
            field=models.CharField(
                default="", max_length=120, verbose_name="Produktname"
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="size",
            field=models.CharField(default="", max_length=60, verbose_name="Größe"),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="vat_rate",
            field=models.DecimalField(
                choices=[
                    (Decimal("19.00"), "19 %"),
                    (Decimal("7.00"), "7 %"),
                    (Decimal("0.00"), "0 %"),
                ],
                decimal_places=2,
                default=Decimal("19.00"),
                max_digits=4,
                verbose_name="Mehrwertsteuersatz",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zwei bis vier Buchstaben, z. B. EW. Bildet den Anfang der Produktnummer.",
                max_length=4,
                verbose_name="Kürzel",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="next_number",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Nächste laufende Nummer"
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="inventory_no",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="Produktnummer"
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_items",
                to="shop.product",
                verbose_name="Produkt (Vorlage)",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="received_at",
            field=models.DateField(blank=True, null=True, verbose_name="Lieferdatum"),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.supplier",
                verbose_name="Hersteller",
            ),
        ),
        migrations.AlterField(
            model_name="stockitemevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("eingang", "Wareneingang"),
                    ("phase", "Fertigungsphase"),
                    ("status", "Status"),
                ],
                max_length=10,
            ),
        ),
    ]
