# Generated by Django 5.2.8 on 2026-08-04 16:16

import re

from django.db import migrations, models

BEKANNT = {
    "ellenwille": "EW",
    "deuinghair": "DH",
    "glückssträhnen": "GS",
    "china": "CH",
    "bergmann": "BM",
}


def kuerzel_setzen(apps, schema_editor):
    """Vorhandenen Lieferanten ein eindeutiges Kuerzel geben, bevor die
    Spalte unique wird.
    """
    Supplier = apps.get_model("inventory", "Supplier")
    vergeben = set()
    for lieferant in Supplier.objects.all().order_by("pk"):
        if lieferant.code:
            vergeben.add(lieferant.code)
            continue
        basis = BEKANNT.get(lieferant.name.strip().lower())
        if not basis:
            buchstaben = re.sub(r"[^A-Za-z]", "", lieferant.name).upper()
            basis = buchstaben[:2] or "XX"
        code = basis
        zaehler = 1
        while code in vergeben:
            zaehler += 1
            code = f"{basis[:3]}{zaehler}"
        vergeben.add(code)
        lieferant.code = code
        lieferant.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_wareneingang_felder"),
    ]

    operations = [
        migrations.RunPython(kuerzel_setzen, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                help_text="Zwei bis vier Buchstaben, z. B. EW. Bildet den Anfang der Produktnummer.",
                max_length=4,
                unique=True,
                verbose_name="Kürzel",
            ),
        ),
    ]
