# Generated by Django 5.2.8 on 2026-08-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_supplier_code_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="channel",
            field=models.CharField(
                choices=[("online", "Online"), ("studio", "Studio")],
                default="studio",
                max_length=10,
                verbose_name="Verkaufskanal",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_city",
            field=models.CharField(blank=True, max_length=80, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_street",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Straße und Hausnummer"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_zip",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, verbose_name="Notiz für die Rechnung"),
        ),
        migrations.AddField(
            model_name="order",
            name="sold_on",
            field=models.DateField(blank=True, null=True, verbose_name="Verkaufsdatum"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kunde (Konto)",
            ),
        ),
    ]
