# Generated by Django 5.2.8 on 2026-08-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='audience',
            field=models.CharField(choices=[('b2c', 'Alle Kunden'), ('b2b', 'Nur B2B')], default='b2c', max_length=3, verbose_name='Zielgruppe'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='cap_type',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Montur'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='density',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Dichte'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Shop-Beschreibung'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Im Shop veröffentlicht'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Interne Notizen'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Stückzahl'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Verkaufspreis'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='shop_category',
            field=models.CharField(blank=True, choices=[('bestand', 'Echthaarperücken im Bestand'), ('pflege', 'Pflegeprodukte'), ('zubehoer', 'Perücken Zubehör'), ('topholder', 'Top Holder'), ('rohling', 'Rohlinge (B2B)')], default='', max_length=10, verbose_name='Shop-Kategorie'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_mode',
            field=models.CharField(choices=[('einzelstueck', 'Einzelstück'), ('menge', 'Mengenartikel')], default='einzelstueck', max_length=12, verbose_name='Bestandsart'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='structure',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Schnitt'),
        ),
        migrations.AlterField(
            model_name='stockitemevent',
            name='kind',
            field=models.CharField(choices=[('eingang', 'Wareneingang'), ('phase', 'Fertigungsphase'), ('status', 'Status'), ('shop', 'Shop'), ('projekt', 'Projekt')], max_length=10),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('farbe', 'Farbe'), ('laenge', 'Länge'), ('schnitt', 'Schnitt'), ('montur', 'Montur'), ('dichte', 'Dichte'), ('groesse', 'Größe')], max_length=10, verbose_name='Merkmal')),
                ('name', models.CharField(max_length=80, verbose_name='Wert')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Auswahlwert',
                'verbose_name_plural': 'Auswahlwerte',
                'ordering': ['group', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='uniq_attr_group_name')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('customer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Kundenname')),
                ('target_color', models.CharField(blank=True, default='', max_length=80, verbose_name='Farbe')),
                ('target_length', models.CharField(blank=True, default='', max_length=60, verbose_name='Länge')),
                ('target_structure', models.CharField(blank=True, default='', max_length=60, verbose_name='Schnitt')),
                ('target_cap_type', models.CharField(blank=True, default='', max_length=80, verbose_name='Montur')),
                ('target_density', models.CharField(blank=True, default='', max_length=60, verbose_name='Dichte')),
                ('target_size', models.CharField(blank=True, default='', max_length=60, verbose_name='Größe')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Kommentare')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fertig bis')),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('in_arbeit', 'In Arbeit'), ('fertig', 'Fertig'), ('abgeholt', 'Abgeholt'), ('storniert', 'Storniert')], default='geplant', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Kunde (Konto)')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='inventory.stockitem', verbose_name='Bestandsstück')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory/%Y/%m/', verbose_name='Bild')),
                ('kind', models.CharField(choices=[('eingang', 'Eingangsbild'), ('shop', 'Verkaufsbild')], default='eingang', max_length=10, verbose_name='Art')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Bestandsbild',
                'verbose_name_plural': 'Bestandsbilder',
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
    ]
