# Generated by Django 5.2.8 on 2026-08-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_order_verkaufsdaten"),
        ("shop", "0011_product_track_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="description",
            field=models.CharField(
                default="", max_length=160, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.product",
                verbose_name="Produkt",
            ),
        ),
    ]
