# Generated by Django 5.2.8 on 2026-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_orderitem_bezeichnung"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail-Adresse"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="Name"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="Notiz"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rechnungsempfänger",
                "verbose_name_plural": "Rechnungsempfänger",
                "ordering": ["name", "email"],
            },
        ),
    ]
