# Generated by Django 5.2.8 on 2026-08-17 15:56

from django.db import migrations, models

# Alt -> neu. Der Arbeitsstand haengt jetzt nur noch am Projekt, deshalb
# schrumpfen fuenf Zustaende auf drei.
VORWAERTS = {
    "geplant": "offen",
    "in_arbeit": "offen",
    "fertig": "erledigt",
    "abgeholt": "erledigt",
}
RUECKWAERTS = {"offen": "geplant", "erledigt": "fertig"}


def _umschreiben(apps, schema_editor, zuordnung):
    Project = apps.get_model("inventory", "Project")
    for alt, neu in zuordnung.items():
        Project.objects.filter(status=alt).update(status=neu)


def vorwaerts(apps, schema_editor):
    _umschreiben(apps, schema_editor, VORWAERTS)


def rueckwaerts(apps, schema_editor):
    _umschreiben(apps, schema_editor, RUECKWAERTS)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockitem_audience_stockitem_cap_type_and_more'),
    ]

    operations = [
        migrations.RunPython(vorwaerts, rueckwaerts),
        migrations.RemoveField(
            model_name='stockitem',
            name='current_phase',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('erledigt', 'Erledigt'), ('storniert', 'Storniert')], default='offen', max_length=10, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='ProductionPhase',
        ),
    ]
