# Generated by Django 5.2.8 on 2026-08-17 20:55

from django.db import migrations, models

# Peruecken und Rohlinge sind Einzelstuecke, alles andere ist Mengenware.
# Die Bestandsart wird nicht mehr von Hand gepflegt, deshalb werden bestehende
# Zeilen einmalig auf den zur Kategorie passenden Wert gezogen.
EINZELSTUECK_KATEGORIEN = ("bestand", "rohling")


def bestandsart_angleichen(apps, schema_editor):
    StockItem = apps.get_model("inventory", "StockItem")
    StockItem.objects.filter(
        shop_category__in=EINZELSTUECK_KATEGORIEN
    ).update(stock_mode="einzelstueck")
    StockItem.objects.exclude(
        shop_category__in=EINZELSTUECK_KATEGORIEN
    ).exclude(shop_category="").update(stock_mode="menge")


def rueckwaerts(apps, schema_editor):
    """Nichts zu tun - die alten Werte waren frei waehlbar und sind nicht
    rekonstruierbar. Die Migration bleibt trotzdem umkehrbar.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_phasen_entfernen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Anzahl'),
        ),
        migrations.RunPython(bestandsart_angleichen, rueckwaerts),
    ]
