# Generated by Django 5.2.8 on 2026-08-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_anzahl_und_bestandsart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='target_size',
        ),
    ]
