# Generated by Django 5.1.3 on 2026-08-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_projekt_ohne_zielgroesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='audience',
            field=models.CharField(choices=[('alle', 'Alle Kunden'), ('b2c', 'Nur B2C'), ('b2b', 'Nur B2B')], default='alle', max_length=5, verbose_name='Zielgruppe'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='shop_category',
            field=models.CharField(blank=True, choices=[('echthaar_peruecke', 'Echthaarperücke'), ('echthaar_topper', 'Echthaartopper'), ('kunsthaar_peruecke', 'Kunsthaarperücke'), ('kunsthaar_topper', 'Kunsthaartopper'), ('zubehoer', 'Perücken Zubehör'), ('pflege', 'Pflegeprodukte (Hair Care)')], default='', max_length=20, verbose_name='Shop-Kategorie'),
        ),
    ]
