# Generated by Django 5.1.3 on 2026-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_neue_kategorien_und_zielgruppe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier_article_no',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Artikelnummer des Lieferanten'),
        ),
    ]
