# Generated by Django 5.1.3 on 2026-08-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_stockitem_vat_rate_and_more'),
        ('shop', '0015_product_available_variants_product_delivery_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_article_no', models.CharField(max_length=60, verbose_name='Artikelnummer des Lieferanten')),
                ('product_name', models.CharField(max_length=120, verbose_name='Produktname')),
                ('shop_category', models.CharField(blank=True, choices=[('echthaar_peruecke', 'Echthaarperücke'), ('echthaar_topper', 'Echthaartopper'), ('kunsthaar_peruecke', 'Kunsthaarperücke'), ('kunsthaar_topper', 'Kunsthaartopper'), ('zubehoer', 'Perücken Zubehör'), ('pflege', 'Pflegeprodukte (Hair Care)')], default='', max_length=20, verbose_name='Shop-Kategorie')),
                ('audience', models.CharField(choices=[('alle', 'Alle Kunden'), ('b2c', 'Nur B2C'), ('b2b', 'Nur B2B')], default='alle', max_length=5, verbose_name='Zielgruppe')),
                ('color', models.CharField(blank=True, default='', max_length=80, verbose_name='Farbe')),
                ('length', models.CharField(blank=True, default='', max_length=60, verbose_name='Länge')),
                ('size', models.CharField(blank=True, default='', max_length=60, verbose_name='Größe')),
                ('structure', models.CharField(blank=True, default='', max_length=60, verbose_name='Schnitt')),
                ('density', models.CharField(blank=True, default='', max_length=60, verbose_name='Dichte')),
                ('cap_type', models.CharField(blank=True, default='', max_length=80, verbose_name='Montur')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Listenpreis des Lieferanten')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Verkaufspreis')),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, help_text='Wird der Kundin auf der Produktseite genannt.', null=True, verbose_name='Lieferzeit (Werktage)')),
                ('availability', models.CharField(choices=[('lieferbar', 'Lieferbar'), ('pausiert', 'Vorübergehend nicht lieferbar'), ('ausgelaufen', 'Ausgelaufen')], default='lieferbar', max_length=12, verbose_name='Lieferbarkeit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Wird angeboten')),
                ('description', models.TextField(blank=True, default='', verbose_name='Shop-Beschreibung')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_colors', models.ManyToManyField(blank=True, related_name='catalog_colors', to='inventory.attributeoption', verbose_name='Auch erhältlich in diesen Farben')),
                ('available_sizes', models.ManyToManyField(blank=True, related_name='catalog_sizes', to='inventory.attributeoption', verbose_name='Auch erhältlich in diesen Größen')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='shop.product', verbose_name='Produkt (Shop)')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='inventory.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Bestellartikel',
                'verbose_name_plural': 'Bestellware',
                'ordering': ['product_name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='inventory.catalogitem', verbose_name='Bestellartikel'),
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='katalog/%Y/%m/', verbose_name='Bild')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.catalogitem')),
            ],
            options={
                'verbose_name': 'Bild zum Bestellartikel',
                'verbose_name_plural': 'Bilder zur Bestellware',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('supplier', 'supplier_article_no'), name='uniq_lieferant_artikelnummer'),
        ),
    ]
