# Generated by Django 5.2.8 on 2026-07-06 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('label', models.CharField(max_length=60, verbose_name='Kurzlabel')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('damen', 'Damen'), ('herren', 'Herren')], max_length=10, verbose_name='Kategorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preis (ab)')),
                ('badge', models.CharField(blank=True, choices=[('new', 'Neu'), ('popular', 'Beliebt')], default='', max_length=10, verbose_name='Badge')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warenkorb',
                'verbose_name_plural': 'Warenkörbe',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Warenkorb-Position',
                'verbose_name_plural': 'Warenkorb-Positionen',
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_product')],
            },
        ),
    ]
