# Generated by Django 5.2.8 on 2026-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audience',
            field=models.CharField(choices=[('b2c', 'Alle Kunden'), ('b2b', 'Nur B2B')], default='b2c', max_length=3, verbose_name='Zielgruppe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('damen', 'Damen'), ('herren', 'Herren'), ('pflege', 'Pflege'), ('rohling', 'Rohlinge')], max_length=10, verbose_name='Kategorie'),
        ),
    ]
