# Generated by Django 5.2.8 on 2026-07-07 06:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_audience_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguratorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Konfigurator-Gruppe',
                'verbose_name_plural': 'Konfigurator-Gruppen',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cap_type',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Monturart'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_notes',
            field=models.TextField(blank=True, default='', verbose_name='Pflegehinweise'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_amount',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Inhalt / Menge'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_color',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Haarfarbe'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_length',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Haarlänge'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_origin',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Haarherkunft'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_structure',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Haarstruktur'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_notes',
            field=models.TextField(blank=True, default='', verbose_name='Anwendung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('konfig', 'Echthaarperücken konfigurierbar'), ('bestand', 'Echthaarperücken im Bestand'), ('pflege', 'Pflegeprodukte'), ('rohling', 'Rohlinge (B2B)')], max_length=10, verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='ConfiguratorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Bezeichnung')),
                ('surcharge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Aufpreis')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.configuratorgroup')),
            ],
            options={
                'verbose_name': 'Konfigurator-Option',
                'verbose_name_plural': 'Konfigurator-Optionen',
                'ordering': ['group', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='uniq_group_option')],
            },
        ),
    ]
