# Generated by Django 5.2.8 on 2026-07-07 06:02

from django.db import migrations


def forwards(apps, schema_editor):
    Product = apps.get_model("shop", "Product")

    # Herrenperücken werden ersatzlos aus dem Sortiment genommen.
    # Achtung: CASCADE entfernt zugehörige CartItem-Positionen aus
    # Server-Warenkörben eingeloggter Nutzer — für die Demo-Daten gewollt.
    Product.objects.filter(category="herren").delete()

    # Damenperücken werden zu "Echthaarperücken im Bestand".
    # Der Slug-Prefix muss mitwandern, weil seed_products per
    # slugify(f"{category}-{label}") + get_or_create arbeitet — ohne
    # Rewrite entstünden beim nächsten Seed Duplikate (bestand-* neben damen-*).
    for product in Product.objects.filter(category="damen"):
        product.category = "bestand"
        if product.slug.startswith("damen-"):
            base = "bestand-" + product.slug[len("damen-"):]
            slug, i = base[:80], 2
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base[:70]}-{i}"
                i += 1
            product.slug = slug
        product.save(update_fields=["category", "slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_configuratorgroup_product_cap_type_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
