# Generated by Django 5.2.8 on 2026-07-07 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product3DAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image_1', models.ImageField(upload_to='products/3d/sources/', verbose_name='Quellbild 1')),
                ('source_image_2', models.ImageField(blank=True, upload_to='products/3d/sources/', verbose_name='Quellbild 2')),
                ('source_image_3', models.ImageField(blank=True, upload_to='products/3d/sources/', verbose_name='Quellbild 3')),
                ('source_image_4', models.ImageField(blank=True, upload_to='products/3d/sources/', verbose_name='Quellbild 4')),
                ('status', models.CharField(choices=[('pending', 'Wartet'), ('processing', 'In Bearbeitung'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=12, verbose_name='Status')),
                ('model_file', models.FileField(blank=True, upload_to='products/3d/models/', verbose_name='3D-Modell (GLB)')),
                ('preview_thumbnail', models.ImageField(blank=True, upload_to='products/3d/thumbs/', verbose_name='Vorschaubild')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehlermeldung')),
                ('is_public', models.BooleanField(default=False, verbose_name='Für Kunden sichtbar')),
                ('provider', models.CharField(blank=True, default='', max_length=30, verbose_name='3D-Dienst')),
                ('provider_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('comp_offset_x', models.FloatField(default=0.0, verbose_name='Versatz X')),
                ('comp_offset_y', models.FloatField(default=0.0, verbose_name='Versatz Y')),
                ('comp_scale', models.FloatField(default=1.0, verbose_name='Skalierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_3d', to='shop.product')),
            ],
            options={
                'verbose_name': '3D-Modell',
                'verbose_name_plural': '3D-Modelle',
                'ordering': ['-created_at'],
            },
        ),
    ]
