# Generated by Django 5.2.8 on 2026-07-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product3dasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hair_density',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Dichte'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_size',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('konfig', 'Echthaarperücken konfigurierbar'), ('bestand', 'Echthaarperücken im Bestand'), ('pflege', 'Pflegeprodukte'), ('zubehoer', 'Perücken Zubehör'), ('topholder', 'Top Holder'), ('rohling', 'Rohlinge (B2B)')], max_length=10, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_structure',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Schnitt'),
        ),
    ]
