# Generated by Django 5.2.8 on 2026-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_hair_density_product_hair_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cap_type',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Montur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_color',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_length',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Länge'),
        ),
    ]
