# Generated by Django 5.2.8 on 2026-07-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_cap_type_alter_product_hair_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Bild')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Produktbild',
                'verbose_name_plural': 'Produktbilder',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
