# Generated by Django 5.1.3 on 2026-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_mode',
            field=models.CharField(choices=[('einzelstueck', 'Einzelstück'), ('menge', 'Mengenartikel')], default='einzelstueck', max_length=12, verbose_name='Bestandsart'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Bestand (nur Mengenartikel)'),
        ),
    ]
