# Generated by Django 5.2.8 on 2026-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_stock_mode_product_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="track_stock",
            field=models.BooleanField(
                default=False,
                help_text="Verfügbarkeit im Shop aus dem Warenbestand ableiten.",
                verbose_name="Bestandsgeführt",
            ),
        ),
    ]
