# Generated by Django 5.1.3 on 2026-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_neue_kategorien_und_zielgruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_variants',
            field=models.TextField(blank=True, default='', verbose_name='Auch erhältlich in'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Lieferzeit (Werktage)'),
        ),
    ]
