"""Demo-Produktdaten fuer die Shop-Seite (Platzhalter, kein echtes Sortiment)."""

DAMEN_PRODUCTS = [
    {"display_name": 'Perücke „Classic“', "label": "CLASSIC", "price": "890", "badge": "popular",
     "desc": "Zeitloses, schulterlanges Modell mit natürlichem Ansatz und glattem Haar."},
    {"display_name": 'Perücke „Long Layers“', "label": "LONG LAYERS", "price": "1.190", "badge": "new",
     "desc": "Voluminöses Langhaarmodell mit fein gestuften Strähnen."},
    {"display_name": 'Perücke „Bob Chic“', "label": "BOB CHIC", "price": "950", "badge": None,
     "desc": "Kinnlanger, glatter Bob mit klarer Kontur."},
    {"display_name": 'Perücke „Curly Volume“', "label": "CURLY VOLUME", "price": "1.290", "badge": None,
     "desc": "Lebendige Locken in warmem Rotbraun für besonders viel Fülle."},
    {"display_name": 'Perücke „Soft Waves“', "label": "SOFT WAVES", "price": "990", "badge": None,
     "desc": "Aschblonde, mittellange Wellen für einen weichen, natürlichen Look."},
    {"display_name": 'Perücke „Silver Elegance“', "label": "SILVER ELEGANCE", "price": "1.050", "badge": None,
     "desc": "Elegantes silbergraues Modell, schulterlang und glatt."},
    {"display_name": 'Perücke „Honey Blonde“', "label": "HONEY BLONDE", "price": "1.150", "badge": None,
     "desc": "Honigblondes, langes Modell mit seidigem Glanz."},
    {"display_name": 'Perücke „Chestnut Layers“', "label": "CHESTNUT LAYERS", "price": "980", "badge": None,
     "desc": "Kastanienbraune, gestufte Längen für natürliche Bewegung."},
    {"display_name": 'Perücke „Platinum Pixie“', "label": "PLATINUM PIXIE", "price": "720", "badge": "new",
     "desc": "Kurzes platinblondes Modell für einen mutigen, modernen Auftritt."},
    {"display_name": 'Perücke „Mahogany Waves“', "label": "MAHOGANY WAVES", "price": "1.020", "badge": None,
     "desc": "Mahagonifarbene Wellen mit warmem Rotschimmer."},
    {"display_name": 'Perücke „Copper Curls“', "label": "COPPER CURLS", "price": "1.080", "badge": None,
     "desc": "Kupferrote Locken, mittellang, für einen lebendigen Auftritt."},
    {"display_name": 'Perücke „Ash Bob“', "label": "ASH BOB", "price": "940", "badge": None,
     "desc": "Aschbrauner Bob mit klarer, pflegeleichter Form."},
    {"display_name": 'Perücke „Golden Layers“', "label": "GOLDEN LAYERS", "price": "1.220", "badge": None,
     "desc": "Goldblonde, lange Strähnen mit feinen Stufen."},
    {"display_name": 'Perücke „Espresso Straight“', "label": "ESPRESSO STRAIGHT", "price": "1.010", "badge": None,
     "desc": "Tiefbraunes, glattes Langhaarmodell mit intensivem Glanz."},
    {"display_name": 'Perücke „Rose Gold Waves“', "label": "ROSE GOLD WAVES", "price": "1.140", "badge": "new",
     "desc": "Rosegüldene Wellen für einen besonders femininen Look."},
    {"display_name": 'Perücke „Caramel Balayage“', "label": "CARAMEL BALAYAGE", "price": "1.090", "badge": None,
     "desc": "Karamellfarbenes Balayage, mittellang mit sanftem Verlauf."},
    {"display_name": 'Perücke „Midnight Black“', "label": "MIDNIGHT BLACK", "price": "1.030", "badge": None,
     "desc": "Tiefschwarzes, glattes Modell in voller Länge."},
    {"display_name": 'Perücke „Champagne Blonde“', "label": "CHAMPAGNE BLONDE", "price": "1.060", "badge": None,
     "desc": "Champagnerblondes, schulterlanges Modell mit feinem Schimmer."},
]

HERREN_PRODUCTS = [
    {"display_name": 'Herrenperücke „Natural“', "label": "NATURAL", "price": "790", "badge": "popular",
     "desc": "Dezentes Kurzhaarmodell mit hauchdünnem Skin-Ansatz."},
    {"display_name": 'Toupet „Comfort“', "label": "COMFORT", "price": "590", "badge": None,
     "desc": "Leichtes, atmungsaktives Toupet zur punktuellen Kaschierung."},
    {"display_name": 'Herrenperücke „Urban Crop“', "label": "URBAN CROP", "price": "750", "badge": "new",
     "desc": "Kurzes, modernes Modell mit texturierter Oberfläche."},
    {"display_name": 'Herrenperücke „Silver Fox“', "label": "SILVER FOX", "price": "820", "badge": None,
     "desc": "Silbergraues Kurzhaarmodell für einen souveränen Auftritt."},
    {"display_name": 'Herrenperücke „Classic Side Part“', "label": "CLASSIC SIDE PART", "price": "770", "badge": None,
     "desc": "Klassischer Seitenscheitel in natürlichem Braun."},
    {"display_name": 'Herrenperücke „Textured Crew“', "label": "TEXTURED CREW", "price": "800", "badge": None,
     "desc": "Dunkelblondes, texturiertes Modell mit lebendiger Struktur."},
    {"display_name": 'Herrenperücke „Executive“', "label": "EXECUTIVE", "price": "810", "badge": None,
     "desc": "Seriöses, kurzes Modell in dunkelbraun für den Business-Alltag."},
    {"display_name": 'Herrenperücke „Salt & Pepper“', "label": "SALT & PEPPER", "price": "850", "badge": None,
     "desc": "Salz-und-Pfeffer-Melange für einen natürlich gereiften Look."},
    {"display_name": 'Herrenperücke „Fade Cut“', "label": "FADE CUT", "price": "780", "badge": None,
     "desc": "Schwarzes Modell mit modernem Fade-Schnitt."},
    {"display_name": 'Toupet „Light“', "label": "TOUPET LIGHT", "price": "610", "badge": None,
     "desc": "Hellbraunes, besonders leichtes Toupet für den Alltag."},
    {"display_name": 'Toupet „Precision“', "label": "TOUPET PRECISION", "price": "630", "badge": None,
     "desc": "Präzise gearbeitetes Toupet in dunkelbraun."},
    {"display_name": 'Herrenperücke „Grey Blend“', "label": "GREY BLEND", "price": "840", "badge": None,
     "desc": "Grau-braun melierter Kurzhaarschnitt für einen natürlichen Grauverlauf."},
]
